library(knitr)
library(dplyr)
library(ggplot2, echo = TRUE))
activity<- read_csv("~/R/UCI HAR Dataset.csv/activity.csv")
data <- activity[ with (activity, { !(is.na(steps)) } ), ]
head(data,20)
str(data)

##Histogram of the total number of steps taken each day
total.info <- tapply(data$steps, data$date, FUN=sum, na.rm=TRUE)
hist(total.info )
# Create mean and median of steps per day
qplot(total.info, binwidth=1000, xlab="total number of steps taken each day")<-mean(total.info,na.rm=TRUE)
stepmedianday<-median(total.info,na.rm=TRUE)
stepmeanday<-mean(total.info,na.rm=TRUE)
##Time series plot of the average number of steps taken
library(ggplot2)
steps_by_interval <- aggregate(x=list(steps=data$steps), by=list(interval=data$interval),FUN=mean, na.rm=TRUE)
ggplot(data=steps_by_interval, aes(x=interval, y=steps)) +
  geom_line() +
  ggtitle("Average number of steps over all days) +
  xlab("5-minute interval") +
  ylab("average number of steps taken")

##the 5-minute interval that, on average, contains the maximum number of steps.
steps_by_interval[which.max(steps_by_interval$steps),]
##describe and show a strategy for imputing missing 
sum(is.na(activity))

##original dataset but with the missing data filled in
for (i in 1:nrow(activity)){
          if (is.na(activity$steps[i])){
          interval_val <- activity$interval[i]
          row_id <- which(table_interval_steps$interval==interval)
          steps_val <- table_interval_steps$steps[row_id]
          activity$steps[i] <- steps_val
          }
}
table_date_steps_edited <- aggregate(steps ~ date, activity, sum)
hist(table_date_steps_edited, col=2, main= "Edited Histogarm total number of steps taken each day",
xlab="Total number of steps in a day")

##the means are the same however the median has a slight change
mean(table_date_steps_edited$steps)
median(table_date_steps_edited$steps)
activity1<-aggregate(interval_val~steps)

##Are there differences in activity patterns between weekdays and weekends?
activity$data<-as.date(activity$date)
activity$day<-weesks(activity$date)
activityday_type<-c("weekday")
for (i in 1:nrow(activity)){
  if (activity$day[i] == "Saturday" || df$day[i] == "Sunday"){
activity$day_type[i] <- "weekend"
}
}
activity$day_type <- as.factor(activity$day_type)
table_date_steps_edited <- aggregate(steps ~ interval+day_type, activity, mean)
qplot(interval, steps, data=table_date_steps_edited, geom=c("line"), xlab="Interval", 
      ylab="Number of steps", main="") + facet_wrap(~ day_type, ncol=1)
